# generated by datamodel-codegen:
#   filename:  action.schema.json
#   timestamp: 2025-09-17T01:17:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class Kind(Enum):
    ATTACK = "ATTACK"
    CHECK = "CHECK"
    SAVE = "SAVE"
    CAST = "CAST"
    MOVE = "MOVE"
    USE = "USE"
    TALK = "TALK"
    OTHER = "OTHER"


class Ability(Enum):
    Str = "Str"
    Dex = "Dex"
    Con = "Con"
    Int = "Int"
    Wis = "Wis"
    Cha = "Cha"


class Action(BaseModel):
    actor_id: str
    kind: Kind
    target: Optional[str] = None
    ability: Optional[Ability] = None
    skill: Optional[str] = None
    advantage: Optional[bool] = None
    disadvantage: Optional[bool] = None
    notes: Optional[str] = None
