/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Action {
  actor_id: string;
  kind: "ATTACK" | "CHECK" | "SAVE" | "CAST" | "MOVE" | "USE" | "TALK" | "OTHER";
  target?: string;
  ability?: "Str" | "Dex" | "Con" | "Int" | "Wis" | "Cha";
  skill?: string;
  advantage?: boolean;
  disadvantage?: boolean;
  notes?: string;
  [k: string]: unknown;
}
