/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GameState {
  meta: {
    campaign_id?: string;
    turn?: number;
    datetime?: string;
    difficulty?: "easy" | "normal" | "hard";
    [k: string]: unknown;
  };
  party: string[];
  characters: {
    [k: string]: Character;
  };
  npcs?: {
    [k: string]: Character;
  };
  locations?: {
    [k: string]: {
      name?: string;
      tags?: string[];
      notes?: string;
      [k: string]: unknown;
    };
  };
  quests?: {
    [k: string]: {
      name?: string;
      status?: "active" | "completed" | "failed";
      objectives?: string[];
      [k: string]: unknown;
    };
  };
  flags?: {
    [k: string]: boolean;
  };
  log: {
    t?: number;
    type?: "ROLL" | "ACTION" | "EVENT" | "NARRATION";
    detail?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface Character {
  /**
   * Unique character ID
   */
  id: string;
  name: string;
  level: number;
  class:
    | "Barbarian"
    | "Bard"
    | "Cleric"
    | "Druid"
    | "Fighter"
    | "Monk"
    | "Paladin"
    | "Ranger"
    | "Rogue"
    | "Sorcerer"
    | "Warlock"
    | "Wizard";
  race: "Human" | "Elf" | "Dwarf" | "Halfling" | "Dragonborn" | "Gnome" | "Half-Elf" | "Half-Orc" | "Tiefling";
  alignment?: string;
  abilities: {
    str: number;
    dex: number;
    con: number;
    int: number;
    wis: number;
    cha: number;
    [k: string]: unknown;
  };
  proficiencies?: {
    skills?: string[];
    saves?: string[];
    weapons?: string[];
    armor?: string[];
    tools?: string[];
    [k: string]: unknown;
  };
  ac: number;
  hp: {
    current: number;
    max: number;
    temp?: number;
    [k: string]: unknown;
  };
  speed: number;
  inventory?: {
    [k: string]: unknown;
  }[];
  spells?: {
    [k: string]: unknown;
  }[];
  features?: string[];
  conditions?: (
    | "Blinded"
    | "Charmed"
    | "Deafened"
    | "Frightened"
    | "Grappled"
    | "Incapacitated"
    | "Invisible"
    | "Paralyzed"
    | "Petrified"
    | "Poisoned"
    | "Prone"
    | "Restrained"
    | "Stunned"
    | "Unconscious"
    | "Exhaustion"
  )[];
  resources?: {
    [k: string]: number;
  };
  persona?: {
    voice?: string;
    goals?: string[];
    tactics?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
